name: routine
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  easy_localization: ^3.0.0
  flutter_dotenv: ^5.0.2
  shared_preferences: ^2.3.2
  logger: ^2.4.0
  flutter_colorpicker: ^1.0.3
  google_fonts: ^6.2.1
  basic_utils: ^5.7.0
  flutter_markdown: ^0.7.4+1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/
    - assets/images/
    - .env