name: fitness
description: "Fitness app for diet and workout routines."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter

  easy_localization: ^3.0.7
  flutter_dotenv: ^5.2.1
  shared_preferences: ^2.5.5
  http: ^1.2.2
  logger: ^2.5.0
  google_fonts: ^8.1.0
  path_provider: ^2.1.5
  share_plus: ^13.2.0
  pdf: ^3.11.1
  intl: ^0.20.2
  basic_utils: ^5.7.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/i18n/
    - assets/images/
    - .env
