name: routine
description: "An app for routine"

publish_to: 'none' 

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  easy_localization: ^3.0.0
  flutter_dotenv: ^5.0.2
  shared_preferences: ^2.0.6
  logger: ^2.4.0
  flutter_colorpicker: ^1.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/
    - assets/images/
    - .env